create table if not exists public.dispense_workflow(
 id bigint generated by default as identity primary key,
 work_date date not null,
 mrn text not null,
 status text not null default 'waiting',
 staff_id text,
 staff_name text,
 started_at timestamptz,
 completed_at timestamptz,
 updated_at timestamptz default now(),
 unique(work_date,mrn)
);
alter table public.dispense_workflow enable row level security;
create policy "pilot read" on public.dispense_workflow for select to anon,authenticated using(true);
create policy "pilot insert" on public.dispense_workflow for insert to anon,authenticated with check(true);
create policy "pilot update" on public.dispense_workflow for update to anon,authenticated using(true) with check(true);
alter publication supabase_realtime add table public.dispense_workflow;
