
create table if not exists public.dispense_audit_log (
  id bigint generated by default as identity primary key,
  work_date date not null,
  mrn text not null,
  action text not null,
  from_status text,
  to_status text,
  user_id uuid references auth.users(id),
  user_name text,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.dispense_audit_log enable row level security;

drop policy if exists "active users insert audit" on public.dispense_audit_log;
create policy "active users insert audit"
on public.dispense_audit_log for insert
to authenticated
with check (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active=true)
);

drop policy if exists "admins read audit" on public.dispense_audit_log;
create policy "admins read audit"
on public.dispense_audit_log for select
to authenticated
using (public.is_admin());

create index if not exists dispense_audit_log_created_at_idx
on public.dispense_audit_log(created_at desc);

create index if not exists dispense_audit_log_mrn_idx
on public.dispense_audit_log(work_date,mrn);
